### ISSUE TITLE
[API Model] Solar-mini-chat-ja (Upstage)

### ISSUE THREAD

**Issue by jihoo-kim** [llm-jp/awesome-japanese-llm#259]
[NEW] **Upstage LLM Chat API for Japanese**
- Model: `solar-1-mini-chat-ja`
- Context length: 32,768
- Developer: Upstage [[Homepage](https://www.upstage.ai/), [Github](https://github.com/UpstageAI), [HuggingFace](https://huggingface.co/upstage)]
- Release date: 2024.05.22
- Docs: https://developers.upstage.ai/docs/apis/chat
- News: https://www.upstage.ai/feed/tech/solar-mini-chat-ja
- Reported on [Nejumi LLM Leaderboard Neo](https://api.wandb.ai/links/wandb-japan/dcbaznfb)

**Comment by kaisugi** [comment]
Thanks for notifying us of your team's wonderful model! 
It's a great honor to build a new Japanese LLM outside of Japan 😄 
(As a personal note, I love Korean pop-cultures such as movies, dramas and K-pops, and am also highly interested in the current circumstances around Korean LLMs..)

Since `solar-1-mini-chat-ja` seems the first API-based Japanese LLM, I'm now wondering how to post this information on awesome-japanese-llm
Would you like to add the contents on your own, or is it enough if you just check the things I added?

**Comment by jihoo-kim** [comment]
I think it would be enough to add it yourself in the appropriate format.
Thank you for considering adding it.

Also, thank you for this wonderful work.

**Comment by kaisugi** [comment]
OK, I will add it myself
Once I have completed the addition, I will notify you!

**Comment by kaisugi** [comment]
@jihoo-kim 
Hi, I added a new section titled "API-based models" and inserted information about your model

![スクリーンショット 2024-06-01 18 06 48](https://github.com/llm-jp/awesome-japanese-llm/assets/36184621/56b10e29-a4d1-4285-bb4d-714250d9a05b)
https://llm-jp.github.io/awesome-japanese-llm/README_en.html#api-based-models

I hope you like it!
